/* Honey & Thread v0.2. No network, telemetry, remote commands or runtime AI. */
(()=>{'use strict';
const C=window.HoneyCore,$=id=>document.getElementById(id),KEY='anewgam-honey-thread-v02',PREF='anewgam-honey-thread-prefs-v02';
const palettes={dawn:['#f5f0e5','#fffbf2','#263b34','#677368','#d9d3c3','#875338','Peach dawn'],night:['#122e32','#1b393d','#e3f2e9','#aac6c4','#456668','#86d9d2','Cyano night'],honey:['#eee0c3','#fff1d3','#433723','#796944','#d1bd91','#92622e','Honeylight'],reign:['#301f26','#422931','#f7e8dc','#d5b4aa','#69434a','#f0a393','Red reign'],everfallen:['#28293b','#34364a','#e9e4f1','#bdbbd1','#545570','#bfb2e8','Everfallen dusk']};
const coats={potato:'#a78b72',turnip:'#ded5bc',blubaer:'#91afbc',purple:'#b1a0bf',yellow:'#d7b667',red:'#b67564'};
let state=C.newGame(23),action='plant',view='garden',mode='dawn',form='potato',scene=0,journal=[],symbols=false,storageOK=true;
try{const raw=localStorage.getItem(KEY);if(raw)state=C.parseSave(raw);const p=JSON.parse(localStorage.getItem(PREF)||'{}');if(palettes[p.mode])mode=p.mode;if(coats[p.form])form=p.form;symbols=p.symbols===true;if(Array.isArray(p.journal))journal=p.journal.filter(validChoice).slice(-80);}catch(e){storageOK=false;}
function validChoice(x){return x&&Number.isInteger(x.scene)&&x.scene>=0&&x.scene<4&&Number.isInteger(x.choice)&&x.choice>=0&&x.choice<2;}
function status(t){$('notice').textContent=t;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));localStorage.setItem(PREF,JSON.stringify({mode,form,symbols,journal}));storageOK=true;}catch(e){storageOK=false;}$('saveStatus').textContent=storageOK?'Saved in this browser · export to carry your garden.':'Browser storage unavailable · export to keep this garden.';}
function setMode(m,persist=true){if(!palettes[m])return;mode=m;const p=palettes[m];['--paper','--card','--ink','--muted','--line','--accent'].forEach((k,i)=>document.documentElement.style.setProperty(k,p[i]));$('modeLabel').textContent=p[6]+' · appearance only';document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===m)));const plates=window.HoneyArt||[];const plate=plates.find(x=>x.mode===m);document.documentElement.style.setProperty('--ambient',plate?'url("'+plate.src+'")':'none');if(persist)save();}
function baer(){const f=coats[form];return `<g><ellipse cy="6" rx="29" ry="27" fill="${f}" stroke="#665447" stroke-width="2"/><ellipse cx="-23" cy="-15" rx="9" ry="10" fill="${f}" stroke="#665447" stroke-width="2"/><ellipse cx="23" cy="-15" rx="9" ry="10" fill="${f}" stroke="#665447" stroke-width="2"/><ellipse cx="-15" cy="31" rx="10" ry="6" fill="#806b57"/><ellipse cx="15" cy="31" rx="10" ry="6" fill="#806b57"/><path d="M-18-4l10 3M8-1l10-3" stroke="#534738" stroke-width="3" stroke-linecap="round"/><circle cx="-11" cy="5" r="2.5" fill="#302d29"/><circle cx="11" cy="5" r="2.5" fill="#302d29"/><path d="M-5 13h10l-5 5Z" fill="#564738"/><path d="M-8 23q8-5 16 0" fill="none" stroke="#564738" stroke-width="2"/>${form==='turnip'?'<path d="M0-20q-18-24-19-9q4 14 19 9q20-4 14-14q-11-7-14 14" fill="#86996b"/>':form==='blubaer'?'<path d="M-9-21l4-10 8 8 8-9 1 12" fill="#7595a9"/>':''}</g>`;}
function icon(t){if(t.type==='hive')return '<ellipse cy="25" rx="31" ry="10" fill="#9b7b4533"/><path d="M-25 20q0-23 7-27q-2-15 11-17q7-11 14 0q12 3 10 17q9 8 9 27Z" fill="#e7ba65" stroke="#a77d3f" stroke-width="2"/><path d="M-24 11H24M-20-1H20M-15-13H15" stroke="#c0944f" stroke-width="3"/><path d="M-7 20V10q7-13 14 0v10Z" fill="#62533d"/>';
if(t.type==='water')return '<path d="M-24-10q12-9 24 0t24 0M-24 4q12-9 24 0t24 0M-20 18q10-8 20 0t20 0" fill="none" stroke="#def1e6" stroke-width="3"/>';
if(t.type==='flower')return `<g opacity="${t.used?.4:1}"><path d="M0 25V-5M0 13Q-21 14-16 3Q-4 1 0 13M0 19Q20 18 15 6Q3 8 0 19" fill="#77915d" stroke="#657e51" stroke-width="2"/>${[0,60,120,180,240,300].map(a=>`<ellipse cx="0" cy="-17" rx="7" ry="11" transform="rotate(${a} 0 -7)" fill="#ebb6ae" stroke="#b7857e" stroke-width="1"/>`).join('')}<circle cy="-7" r="7" fill="#f2d68a"/></g>`;
return '<path d="M-12 17V1m0 8-8-7m8 2 7-7M15 18V5m0 8 7-5M2-15v-9" stroke="#8c9d74" stroke-width="2.5" fill="none" stroke-linecap="round"/>';}
function renderBoard(){const points=Array.from({length:6},(_,i)=>{const a=(60*i-30)*Math.PI/180;return `${48*Math.cos(a)},${48*Math.sin(a)}`;}).join(' ');const fills={meadow:'#d5dcc1',flower:'#bbcba5',water:'#91b9bc',hive:'#e9d3a3'};let html='<defs><linearGradient id="wood" x2="1" y2="1"><stop stop-color="#cfb795"/><stop offset="1" stop-color="#b49674"/></linearGradient></defs><ellipse cx="370" cy="286" rx="248" ry="221" fill="#75695122"/><ellipse cx="370" cy="271" rx="245" ry="216" fill="#a58a69"/><ellipse cx="370" cy="262" rx="245" ry="214" fill="url(#wood)" stroke="#a78967" stroke-width="2"/><ellipse cx="370" cy="262" rx="231" ry="201" fill="none" stroke="#e0caab" stroke-width="1.5"/>';
for(const t of state.board){const x=370+Math.sqrt(3)*53*(t.q+t.r/2),y=259+79.5*t.r;const block=C.baerAt(state,t.id);html+=`<g class="tile" data-tile="${t.id}" role="button" tabindex="0" aria-label="${t.type} ${t.id}${block?', Baer here':''}${t.used?', resting':''}" transform="translate(${x} ${y})"><polygon points="${points}" transform="translate(0 7)" fill="#8a8973"/><polygon class="face" points="${points}" fill="${t.used?'#c5ccb6':fills[t.type]}" stroke="#e8e5d5" stroke-width="2"/>${block?baer():icon(t)}</g>`;}
html+='<g transform="translate(51 128)">';for(let i=0;i<3;i++)html+=`<g transform="translate(0 ${i*52})" opacity="${i<state.actionsLeft?1:.2}"><ellipse cy="8" rx="22" ry="14" fill="#a68e5c22"/><ellipse cx="-9" cy="-13" rx="8" ry="12" fill="#eaf2e4" stroke="#abb8a3"/><ellipse cx="9" cy="-13" rx="8" ry="12" fill="#eaf2e4" stroke="#abb8a3"/><ellipse rx="20" ry="14" fill="#eac36e" stroke="#b78b48"/><path d="M-6-12V12M4-13V13" stroke="#665c44" stroke-width="6"/><circle cx="14" cy="-3" r="2" fill="#514735"/></g>`;html+='</g><g transform="translate(657 290)"><ellipse cy="44" rx="36" ry="7" fill="#a58a6422"/><path d="M-23 0q-9-21-26-15q14 8 15 27M23-3q34-14 28 9q-6 19-29 14" fill="none" stroke="#bd9060" stroke-width="7"/><path d="M-29-9q-7 48 29 48t29-48Z" fill="#ead5ac" stroke="#bd9060" stroke-width="2"/><path d="M-31-9H31M-14-15H14" stroke="#bd9060" stroke-width="4"/><circle cy="12" r="9" fill="#d8b15b"/><path d="M0 3V22M-8 10H8" stroke="#f5e9ca" stroke-width="2"/></g>';
$('board').innerHTML=html;document.querySelectorAll('[data-tile]').forEach(el=>{const activate=()=>{const id=el.dataset.tile;if(['plant','forage'].includes(action))perform(action,id);else status('Choose Plant or Forage before selecting a tile.');const target=[...document.querySelectorAll('[data-tile]')].find(x=>x.dataset.tile===id);if(target)target.focus({preventScroll:true});};el.onclick=activate;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activate();}};});}
function perform(a,id){const out=C.step(state,a,id);if(out.error){status(out.error);return false;}state=out.state;save();status('');render();return true;}
function render(){$('day').textContent=['Dawn','Daylight','Evening'][3-state.actionsLeft]+' / day '+state.day;$('bees').textContent=state.actionsLeft+' of 3 bees ready';$('nectar').textContent=state.nectar;$('honey').textContent=state.honey;$('story').textContent=state.trace.at(-1).text;$('won').hidden=!state.won;document.querySelectorAll('.cup').forEach((c,i)=>{c.classList.toggle('full',i<state.belong);c.setAttribute('aria-label',i<state.belong?'Filled cup':'Empty cup');});for(const a of ['brew','belong'])document.querySelector(`[data-action="${a}"]`).disabled=!!C.explain(state,a);$('invite').disabled=!!C.explain(state,'invite');$('space').disabled=!!C.explain(state,'space');$('rest').disabled=state.won;$('demo').disabled=state.won;$('baerPortrait').innerHTML=baer();$('baerName').textContent=(form==='blubaer'?'Blubaer':form[0].toUpperCase()+form.slice(1)+' Baer');$('baerText').textContent=state.baer.invited?'He chose a seat. Still a monster; not a pet or a prize.':'One patch is his for now. Other paths are open. Friendship is optional.';renderBoard();if(view==='skein')renderTrace();if(view==='c')renderStory();}
function renderTrace(){for(const [id,entries] of [['localTrace',state.trace.map(x=>`Turn ${x.turn} · ${x.event} — ${x.text}`)],['choiceTrace',journal.map(x=>{const s=window.HoneyStory[x.scene];return s.phase+' — '+s.choices[x.choice][1];})]]){const list=$(id);if(!list)continue;list.replaceChildren();for(const text of entries.length?entries:['No story choice recorded yet.']){const li=document.createElement('li');li.textContent=text;list.append(li);}}}
function renderStory(){if(!$('phaseTrack'))return;const stories=window.HoneyStory;$('phaseTrack').innerHTML=stories.map((s,i)=>`<button class="phase ${i===scene?'active':''}" data-scene="${i}" aria-pressed="${i===scene}" ${s.gate(state)?'':'disabled'}><b>${s.mark}</b>${s.phase}<br><span class="small">${s.gate(state)?'Open':i===1?'Plant a flower':i===2?'Pour one cup':'Finish the teapot'}</span></button>`).join('');if(!stories[scene].gate(state))scene=0;const s=stories[scene];$('storyScene').innerHTML=`<div class="eyebrow">${s.phase} · short playable story scene</div><h2>${s.title}</h2><p class="soft-quote">${s.text}</p><div class="row choice">${s.choices.map((c,i)=>`<button data-choice="${i}">${c[0]}</button>`).join('')}</div><p id="choiceResult" class="small" role="status"></p>`;document.querySelectorAll('[data-scene]').forEach(b=>b.onclick=()=>{scene=Number(b.dataset.scene);renderStory();});document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const choice=Number(b.dataset.choice);journal.push({scene,choice});journal=journal.slice(-80);save();$('choiceResult').textContent=s.choices[choice][1];});}
function setView(v,focus=false){if(!['garden','a','b','c','skein','art'].includes(v))v='garden';view=v;$('gardenView').hidden=v!=='garden';$('notebookView').hidden=v==='garden';document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.view===v)));if(v!=='garden'){$('notebookView').innerHTML=window.HoneyNotebook[v];if(v==='skein')renderTrace();if(v==='c')renderStory();if(v==='art'&&window.HoneyArt){const gallery=$('artGallery');for(const p of window.HoneyArt){const figure=document.createElement('figure'),img=document.createElement('img'),cap=document.createElement('figcaption');img.src=p.src;img.alt=p.title;img.loading='lazy';cap.textContent=p.title+' · generated concept, not a runtime capture';figure.append(img,cap);gallery.append(figure);}}if(focus)$('notebookView').focus({preventScroll:true});}history.replaceState(null,'','#'+v);}
function loadSave(text){const obj=JSON.parse(text);if(obj&&obj.schema==='honey-thread-export-v2'){const game=C.parseSave(JSON.stringify(obj.game));const p=obj.preferences||{};if(!palettes[p.mode]||!coats[p.form]||typeof p.symbols!=='boolean'||!Array.isArray(obj.journal)||obj.journal.length>80||obj.journal.some(x=>!validChoice(x)))throw Error('Invalid preferences or story journal.');return{game,mode:p.mode,form:p.form,symbols:p.symbols,journal:obj.journal.map(x=>({scene:x.scene,choice:x.choice}))};}return{game:C.parseSave(text),mode,form,symbols,journal:[]};}
function exportText(){return JSON.stringify({schema:'honey-thread-export-v2',game:state,preferences:{mode,form,symbols},journal},null,2);}
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{action=b.dataset.action;document.querySelectorAll('[data-action]').forEach(x=>x.classList.toggle('active',x===b));if(action==='brew'||action==='belong')perform(action);else status(action==='plant'?'Choose an empty meadow.':'Choose a flower that has not given today.');});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view,true));$('skeinQuick').onclick=()=>setView('skein',true);document.querySelector('.brand').onclick=e=>{e.preventDefault();setView('garden');};document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('form').value=form;$('form').onchange=()=>{form=$('form').value;save();render();};$('symbols').checked=symbols;document.body.classList.toggle('symbol-only',symbols);$('symbols').onchange=()=>{symbols=$('symbols').checked;document.body.classList.toggle('symbol-only',symbols);save();};$('space').onclick=()=>perform('space');$('invite').onclick=()=>perform('invite');$('rest').onclick=()=>perform('rest');$('demo').onclick=()=>{const a=C.demoAction(state);if(a){action=a.action;document.querySelectorAll('[data-action]').forEach(b=>b.classList.toggle('active',b.dataset.action===action));perform(a.action,a.tile);}};
$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([exportText()],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='honey-thread-garden.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Garden and story journal exported.');};$('importBtn').onclick=()=>$('import').click();$('import').onchange=async()=>{const f=$('import').files[0];if(!f)return;try{if(f.size>65536)throw Error('Save must be under 64 KB.');const next=loadSave(await f.text());if(!confirm('Replace this garden? Export first to keep both.'))return;state=next.game;mode=next.mode;form=next.form;symbols=next.symbols;journal=next.journal;$('form').value=form;$('symbols').checked=symbols;document.body.classList.toggle('symbol-only',symbols);scene=0;setMode(mode,false);save();render();status('Garden and its story restored.');}catch(e){status('Import rejected: '+e.message);}$('import').value='';};$('reset').onclick=()=>{if(!confirm('Start a fresh garden? Export first to keep this one.'))return;state=C.newGame(23);journal=[];scene=0;action='plant';document.querySelectorAll('[data-action]').forEach(b=>b.classList.toggle('active',b.dataset.action===action));save();render();status('A new table, with room to begin.');};window.addEventListener('hashchange',()=>setView(location.hash.slice(1)));setMode(mode,false);render();setView(location.hash.slice(1)||'garden');$('saveStatus').textContent=storageOK?'Local garden · changes save in this browser.':'Storage unavailable or an older save could not be read. Export to keep this garden.';
window.HoneyDebug=Object.freeze({getState:()=>JSON.parse(JSON.stringify(state)),getJournal:()=>JSON.parse(JSON.stringify(journal)),exportText,loadSave});
})();
